### ISSUE TITLE
Implement VSCode plugin interfacing with a stub nuclio 

### ISSUE THREAD

**Issue by pavius** [nuclio/nuclio-vscode#1]
Provide a VSCode plugin that speaks to a nuclio interface and allows the following user flows:

Environments and projects:
1. User should be able to create an environment, choosing one of: Kubernetes, local and stubbed. Each environment receives different attributes:
- Kubernetes: registry (string) and runRegistry (string)
- Local: Should pull (boolean)
- Stubbed: No parameters
2. Within a given environment the user should be able to create projects, providing name and namespace
3. User should be able to delete projects

Functions:
1. Within a given project, user should be able to create a function specifying name and runtime (one of Golang, Python 2.6, Python 3.6, .NET core, PyPy, NodeJS, Java and Shell). This creates two files: `function.yaml` and `handler.<per runtime>`. The `function.yaml` should contain the following:
```
apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
    name: <function name>
    namespace: <function namespace>
spec:
  runtime: <function runtime> 
  handler: <function handler>
```

The `handler` should contain an empty per runtime handler:

Go:
```
package main

import (
	"github.com/nuclio/nuclio-sdk-go"
)

func Handler(context *nuclio.Context, event nuclio.Event) (interface{}, error) {
	return nil, nil
}
```

.NET core:
```
using System;
using Nuclio.Sdk;

public class nuclio
{
  public object handler(Context context, Event eventBase)
  {
  }
}
```

All flavors of Python, PyPy included:
```
def handler(context, event):
	pass
```

NodeJS:
```
exports.handler = function(context, event) {
};
```

2. User should be able to deploy the function
3. User can view list of functions given a project
4. User can delete a function, given project and function name (edited)
